---
- name: pull designated certs from host
  ansible.builtin.fetch:
    src: "{{ certs_remote_prefix }}/{{ server_fqdn }}/{{ item }}"
    dest: "{{ certs_local_prefix }}/{{ server_fqdn }}/"
    # destination folder(s) auto-created
    flat: yes
    fail_on_missing: yes
  loop: "{{ cert_files }}"
    # as created/renewed by certmgr.sh with certbot-dns-route53 and LetsEncrypt
  tags:
    - certspull
...
